names: 
  action: prepare
  template: ^names$
no_names: 
  action: prepare  
  template: ^no\snames$
name: 
  action: prepare  
  template: ^name\s
object_not_for_nat:
  action: prepare  
  template: 
    parentspec: ^object\s
    childspec: ^\snat\s
    find_obj_mode: without
object_for_nat:
  action: prepare  
  template:   
    parentspec: ^object\s
    childspec: ^\snat\s
    find_obj_mode: with
object-group: 
  action: prepare  
  template: ^object-group\s
time-range: 
  action: prepare  
  template: ^time-range\s
access-list: 
  action: prepare  
  template: ^access-list\s
class-map: 
  action: prepare  
  template: ^class-map\s
flow-export: 
  action: prepare  
  template: ^flow-export\s
policy-map: 
  action: prepare  
  template: ^policy-map\s
service-policy: 
  action: prepare  
  template: ^service-policy\s
access-group: 
  action: prepare  
  template: ^access-group\s
nat: 
  action: prepare  
  template: ^nat\s
